<template>
  <div class="min-h-screen bg-black text-white">
    <div v-if="loading" class="flex items-center justify-center h-screen">
      <div class="w-8 h-8 rounded-full border-2 border-white/10 border-t-white animate-spin"></div>
    </div>

    <div v-else-if="!lookbook" class="flex items-center justify-center h-screen">
      <p class="text-white/50">Lookbook not found.</p>
    </div>

    <div v-else>
      <!-- Cover page -->
      <div class="relative h-screen flex items-end justify-center pb-20 overflow-hidden">
        <img v-if="coverImage" :src="coverImage" class="absolute inset-0 w-full h-full object-cover opacity-70" />
        <div class="absolute inset-0 bg-gradient-to-t from-black via-black/30 to-transparent"></div>
        <div class="relative z-10 text-center px-6">
          <p class="font-display text-sm tracking-[0.3em] text-white/60 mb-3">{{ lookbook.brand?.name }}</p>
          <h1 class="font-display text-5xl sm:text-7xl text-white italic">{{ lookbook.title }}</h1>
          <p v-if="lookbook.description" class="mt-4 text-white/50 max-w-md mx-auto">{{ lookbook.description }}</p>
          <button @click="scrollDown" class="mt-8 btn-ghost border-white/20 text-white/70 hover:text-white">
            View Lookbook ↓
          </button>
        </div>
      </div>

      <!-- Asset pages -->
      <div ref="pagesRef" class="space-y-1">
        <div v-for="(asset, i) in assets" :key="asset.id"
          class="relative overflow-hidden"
          :class="i % 3 === 0 ? 'h-screen' : i % 3 === 1 ? 'aspect-square' : 'aspect-[4/3]'">
          <img :src="`/storage/${asset.file_path}`"
            class="w-full h-full object-cover" />
        </div>
      </div>

      <!-- Footer -->
      <div class="py-20 text-center border-t border-white/10">
        <p class="font-display text-2xl italic text-white/60">{{ lookbook.title }}</p>
        <p class="text-white/30 text-sm mt-2">Generated by Aces Model</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import api from '@/lib/api'

const route   = useRoute()
const loading = ref(true)
const lookbook = ref(null)
const pagesRef = ref(null)

const assets = computed(() => lookbook.value?.assets ?? [])
const coverImage = computed(() => {
  const first = assets.value.find(a => a.file_path)
  return first ? `/storage/${first.file_path}` : null
})

onMounted(async () => {
  try {
    const { data } = await api.get(`/lookbooks/${route.params.slug}`)
    lookbook.value = data
  } catch {} finally { loading.value = false }
})

function scrollDown() {
  pagesRef.value?.scrollIntoView({ behavior: 'smooth' })
}
</script>
